version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "*"
      BACKEND_URL: "*"
    image: backend-flask:latest
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
    image: frontend-flask:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js

networks: 
  internal-network:
    driver: bridge
    name: cruddur